baseURL = "https://waldorfkindergartern-konstanz.de"
title = "Waldorfkindergarten Konstanz"

theme = ["waldorfkn", "hugomods-images", "hugo-cloak-email"]
# Site languages. Available translations in the theme's `/i18n` directory.
languageCode = "de"
defaultContentLanguage = "de"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

disableKinds = ["taxonomy"]

# Define the number of posts per page
[pagination]
pagerSize = 10

# German quotation marks
[markup.goldmark.extensions.typographer]
    leftDoubleQuote = '„'
    rightDoubleQuote = '“'

[menu]

# Main menu
# [[menu.main]]
#     name       = "Start"
#     identifier = "menu.home"
#     url        = "/"
#     weight     = 1

[[menu.main]]
    name = "Angebot"
    identifier = "angebot"
    weight = 2
    url = ""

[[menu.main]]
    name = "Pädagogik"
    identifier = "pädagogik"
    weight = 3
    url = ""

[[menu.main]]
    name = "Organisatorisches"
    identifier = "organisatorisches"
    weight = 4
    url = ""

[params]
    viewMorePostLink = "/blog/"
    author = "Waldorfkindergarten Konstanz"
    defaultKeywords = []
    mainSections = ["news"]
    eventSections = ["events"]
    defaultDescription = "Mit Herz und Verstand: Waldorfpädagogik von der Krippe bis zum Kindergarten – ganzheitlich, naturverbunden und familiär."

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Format dates with Go's time formatting
    date_format = "02 January 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Waldorfkindergarten Konstanz"

    logo_xs = "images/logo-long.png"
    logo_sm = "images/logo-long.png"
    logo_md = "images/logo.png"
    logo_lg = "images/logo-long.png"
    contact_url = "/kontakt/"
    contact_address = """Freier Waldorfkindergarten Konstanz\\
    Mannheimer Straße 2, 78467 Konstanz"""
    contact_phone = "+49 7531 929796"
    contact_email = "info@waldorfkindergarten-konstanz.de"

    matomo_siteid = 16

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000
    background_image = "images/stock/blaetter.jpg"

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.parallax1]
    enable = true
    background_image = "images/stock/pinsel-hand.jpg"
    image_crop = "1900x1000 Bottom"
    title = "\"Die Kinder schulden uns keine Dankbarkeit dafür, dass wir sie erziehen. Vielmehr haben wir ihnen dankbar dafür zu sein, dass sie sich uns anvertrauen und unser Leben mit Licht erfüllen.\""
    subtitle = "*-- Janusz Korczak*"

[params.events]
    enable = true
    title = "Veranstaltungen"
    subtitle = "Große und kleine Veranstaltungen und Feste sind fester Bestandteil des Kindergartenjahres. Sie sind eine hervorragende Möglichkeit für Kinder, Eltern und Erzieher:innen, sich besser kennenzulernen und gemeinsam Zeit zu verbringen. Darüber hinaus verbinden sie uns mit der Nachbarschaft und bieten Interessierten einen tollen Einblick."
    hide_summary = true
    limit = 5

[params.footer.menu1]
    enable = true
    headline = "Service"

[params.footer.menu2]
    enable = true
    headline = "Organisatorisches"

[params.footer.recent_posts]
    enable = false

[params.footer]
    copyright = "© Verein zur Förderung der Waldorf Pädagogik e.V. seit 1989"
    links = "[Impressum und Datenschutz](/impressum/) | [Credits](/credits/)"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# Modules
[module]
    [[module.mounts]]
        source = "static/img"
        target = "assets/images"
    [[module.mounts]]
        source = "themes/waldorfkn/static/img"
        target = "assets/images"

[build]
[[build.cacheBusters]]
source = 'assets/scss/.*\.scss'
target = 'css'
