name = "Waldorfkindergarten Konstanz"
license = "MIT"
licenselink = "https://github.com/waldorfkn/website/blob/main/themes/waldorfkn/LICENSE"
description = "A fork of the Universal Hugo theme"
homepage = "https://github.com/waldorfkn/website/tree/main/themes/waldorfkn"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive"]
features = ["blog", "themes", "disqus", "minimal", "responsive"]
min_version = 0.139

[author]
    name = "mxmehl"
    homepage = "https://github.com/mxmehl"

# If Porting existing theme
[original]
    author =  "bootstrapious"
    homepage = "http://bootstrapious.com/p/universal-business-e-commerce-template"
