name: Website build and deploy

on:
  push:
    branches: [main] # Deploy branch
  # Run on PRs, but only build
  pull_request:
    types: [opened, reopened, synchronize, closed]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Schedule for automatic deployment, once a day
  schedule:
    - cron: "42 3 * * *"

# Set permissions
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Set environment variables
env:
  domain_production: waldorfkindergarten-konstanz.de
  domain_preview: preview.waldorfkindergarten-konstanz.de
  condition_production: ${{ github.ref == 'refs/heads/main' }}
  dir_preview_subdir: pr-${{ github.event.number }}
  artifact_name: website

jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: recursive # Get submdules
          fetch-depth: 1 # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: false

      - name: Setup required build tools with mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

      - name: Create configuration for Matomo
        run: |
          mv static/config.php.sample static/config.php
          sed -i "s|__PIWIK_URL__|${{ secrets.MATOMO_PIWIK_URL }}|" static/config.php
          sed -i "s|__PROXY_URL__|https://${{ env.domain_production }}|" static/config.php
          sed -i "s|__TOKEN_AUTH__|${{ secrets.MATOMO_TOKEN_AUTH }}|" static/config.php

      - name: Build website with Hugo (production)
        run: hugo -b https://${{ env.domain_production }}
        if: env.condition_production == 'true'

      - name: Build website with Hugo (preview)
        run: hugo -b https://${{ env.domain_preview }}/${dir_preview_subdir} -e staging --buildFuture --buildDrafts
        if: github.event.pull_request

      - name: Upload website artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.artifact_name }}
          path: public
          include-hidden-files: true
          retention-days: 1

  deploy:
    name: Deploy website
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      # pull-requests: write # required unless you explicitly set sticky_comment_enabled: false
      deployments: write # required if gh_deployment is set
    steps:
      - uses: OpenRailAssociation/web-deployment-action@ec2b90e1fe811972e5cee9861646360a7a4356ac # v1.3.0
        with:
          artifact_name: ${{ env.artifact_name }}
          condition_production: ${{ env.condition_production }}
          domain_production: https://${{ env.domain_production }}
          domain_preview: https://${{ env.domain_preview }}
          dir_base: /var/www/virtual/waldorfk
          dir_production: html
          dir_preview_base: ${{ env.domain_preview }}
          dir_preview_subdir: ${{ env.dir_preview_subdir }}
          ssh_host: ${{ env.domain_production}}
          ssh_user: waldorfk
          ssh_key: ${{ secrets.SSH_KEY }}
          # Info options
          sticky_comment_enabled: false
          step_summary_enabled: false
          gh_deployment: preview
          linkchecker_exclude: www.pexels.com
